### ISSUE TITLE
Hide music sidebar from players

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-sound-enhancements#12]
Players don't always need to know what's playing, especially if the song title gives away information. And they can't play songs themselves. So it would be nice to be able to hide that tab entirely from them.

**Comment by weepingminotaur** [comment]
Wait, you do need the global volume control if you're a player. So maybe just hide the Currently Playing control?

**Comment by ironmonk88** [comment]
I think the currently playing should still show since there is a volume slider for that sound as well.
But Sound Enhancements will hide the name of the sound that's currently playing.
![image](https://user-images.githubusercontent.com/75920956/232277860-111c5981-ed1a-4360-87a0-fe8cbe56d9b8.png)

Which might solve your issue?

**Comment by weepingminotaur** [comment]
Yep, my bad. :) Didn't realize that. Carry on and ignore this request.

**Comment by weepingminotaur** [comment]
Actually, on second thought, even when sounds are hidden, the user can still see the name of the playlist those sounds are coming from. Any chance the "Hide Sound Names" could extend to hiding playlist names too? Or another toggle for hiding playlists?

**Comment by ironmonk88** [comment]
That I can do.

**Comment by ironmonk88** [comment]
Added to the latest release.
